baseURL = "http://www.cssillustrations.com/"
languageCode = "en-us"
title = "CSS ILLUSTRATIONS"

theme = "solid"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Publicaciones"
    url        = "posts/"
    weight      = -110
  [[menu.main]]
    identifier = "about"
    name       = "Sobre mi"
    url        = "/about"
    weight    = -100
[[menu.main]]
    identifier = "tsum"
    name       = "Curso Tsum"
    url        = "/tags/tsum"
    weight    = -120

[params]
  defaultImage = "dino.png"
  disqusShortname = "neusageravalls"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"