baseURL = "http://www.cssillustrations.com/"
languageCode = "en-us"
title = "CSS ILLUSTRATIONS"

theme = "solid"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

[params]
  defaultImage = "gopher.jpg"
  disqusShortname = "neusageravalls"