baseURL = "https://cssillustrations.com/"
languageCode = "en-us"
title = "CSS ILLUSTRATIONS"
defaultContentLanguage = "es"
languageName = "es"

theme = "solid"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Publicaciones"
    url        = "posts/"
    weight      = -110
  [[menu.main]]
    identifier = "about"
    name       = "Sobre mi"
    url        = "/about/"
    weight    = -100
[[menu.main]]
    identifier = "tsum"
    name       = "Curso Tsum"
    url        = "/tags/tsum/"
    weight    = -120

[params]
  defaultImage = "dino.png"
  disqusShortname = "neusageravalls"
  socialImage = "presentation.png"
  twitterImage = "presentationTwitter.png"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
