baseURL = "https://cssillustrations.com/"
languageCode = "en-us"
title = "CSS ILLUSTRATIONS"
defaultContentLanguage = "es"
languageName = "es"
theme = "solid"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Publicaciones"
    url        = "posts/"
    weight      = -110
  [[menu.main]]
    identifier = "about"
    name       = "Sobre mi"
    url        = "/about/"
    weight    = -100
[[menu.main]]
    identifier = "tsum"
    name       = "Curso Tsum"
    url        = "/tags/tsum/"
    weight    = -120

[params]
  defaultImage = "dino.png"
  disqusShortname = "neusageravalls"
  socialImage = "presentation.png"
  twitterImage = "presentationTwitter.png"
  author = "Neus Ag체era Valls"
  keywords= "HTML,CSS,illustations,ilustraciones,desarrollo,tutorials,tutoriales,programming,programaci처n,training,learning,lessons,cursos,references,referencias,examples,ejemplos,exercises,ejercicios,source code,c처digo,c처digo limpio,colors,colores,demos,tips,jokes,css jokes,css illustrations,css,less,sass"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
